/* Provide a list of whitelisted licenses for the project below */
const whitelist = [
  '(MIT AND BSD-3-Clause)',
  '(MIT AND CC-BY-3.0)',
  '(MIT AND Zlib)',
  '(MIT OR Apache-2.0)',
  '(MIT OR CC0-1.0)',
  '(WTFPL OR MIT)',
  '0BSD',
  'AFLv2.1',
  'Apache-2.0',
  'Apache2',
  'Artistic-2.0',
  'BSD-2-Clause',
  'BSD-3-Clause OR MIT',
  'BSD-3-Clause',
  'CC-BY-3.0',
  'CC-BY-4.0',
  'CC0-1.0',
  'ISC',
  'MIT',
  'MIT,Apache2',
  'MPL-1.0',
  'MPL-1.1',
  'MPL-2.0-no-copyleft-exception',
  'MPL-2.0',
  'ODC-By-1.0',
  'Unlicense',
  'WTFPL',
  'Zlib',
];

module.exports = whitelist;
